#!/bin/bash
go run main.go 2
go run main.go 3
go run main.go 4
go run main.go 5
go run main.go 6
go run main.go 7
go run main.go 8
go run main.go 9
go run main.go 10
go run main.go 11
go run main.go 12
go run main.go 13
go run main.go 14
go run main.go 15
go run main.go 16
go run main.go 17
go run main.go 18
go run main.go 19
go run main.go 20
go run main.go 21
